name: My Solar System Workflow

on: 
  workflow_dispatch
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install NodeJs
        run: sudo apt install nodejs -y

      - name: Install Dependacies
        run: npm install

      - name: Unit Testing
        run: npm test